// app/layout.js
import { Outfit } from "next/font/google";
import "./globals.css";


// ✅ Google Font config
const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// ✅ Metadata
export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

// ✅ Layout Component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* ✅ suppressHydrationWarning is a safe fallback if an extension adds attributes */}
      <body
        className={outfit.variable}
        style={{ background: "#f9f9f9" }}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
